version: '3.8'
services:
  app:
    image: scrapingfacebookelyadata:1.1.1
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/facebook_scraping_db
      - ACCESS_TOKEN=your_access_token_here
    restart: always

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    restart: always

volumes:
  mongo-data:
